[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; connect-src 'self' https://*.supabase.co; frame-ancestors 'none';"

[[redirects]]
  from = "/out/*"
  to = "/api/out/:splat"
  status = 200